# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('api_version', models.CharField(max_length=10)),
                ('isConnected', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Leaf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=250)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Leaf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('units', models.CharField(max_length=10)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Leaf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booleandevice',
            name='leaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Leaf'),
        ),
    ]
