# Generated by Django 2.1 on 2018-08-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datastore',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leaf',
            options={},
        ),
    ]
