# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Leaf')),
            ],
        ),
        migrations.RemoveField(
            model_name='booleandevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booleandevice',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='booleandevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='numberdevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='numberdevice',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='numberdevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stringdevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stringdevice',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='stringdevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unitdevice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='unitdevice',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='unitdevice',
            name='name',
        ),
        migrations.AddField(
            model_name='booleandevice',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberdevice',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stringdevice',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitdevice',
            name='device_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Device'),
            preserve_default=False,
        ),
    ]
